activation: ReLU
alias: null
batch_size: 32
drop_last_loader: false
dropout_prob_theta: 0.0
early_stop_patience_steps: -1
exclude_insample_y: false
futr_exog_list: null
h: 15
hist_exog_list:
- nb_cars_cxl
- nb_bookings
- nb_bookings_cxl
- hourly rate
- WE package
- 1 week package
- 1 month package
- other package
- 2 weeks package
- turnover
- discount
- booking_fees
- lead_time_hours
- standard
- premium
- "6H \xE0 9H"
- "15H \xE0 18H"
- "9H \xE0 12H"
- "12H \xE0 15H"
- "0H \xE0 6H"
- "18H \xE0 24H"
- +24h
- 06:00 24:00
- 00:30 06:00
- 00:00 00:30
- strike
- holidays
- vacation
inference_windows_batch_size: -1
input_size: 30
learning_rate: 0.001
loss: !!python/object:neuralforecast.losses.pytorch.MAE
  _backward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _backward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _buffers: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _forward_pre_hooks_with_kwargs: !!python/object/apply:collections.OrderedDict
  - []
  _is_full_backward_hook: null
  _load_state_dict_post_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _load_state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _modules: !!python/object/apply:collections.OrderedDict
  - []
  _non_persistent_buffers_set: !!set {}
  _parameters: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_hooks: !!python/object/apply:collections.OrderedDict
  - []
  _state_dict_pre_hooks: !!python/object/apply:collections.OrderedDict
  - []
  is_distribution_output: false
  output_names:
  - ''
  outputsize_multiplier: 1
  training: false
max_steps: 1000
mlp_units:
- &id001
  - 512
  - 512
- *id001
- *id001
n_blocks:
- 1
- 1
- 1
n_harmonics: 2
n_polynomials: 2
num_lr_decays: 3
num_workers_loader: 0
random_seed: 1
scaler_type: identity
shared_weights: false
stack_types:
- identity
- trend
- seasonality
stat_exog_list: null
step_size: 1
val_check_steps: 100
valid_batch_size: null
valid_loss: null
windows_batch_size: 1024
